// Pozivni brojevi — Srbija je podrazumevana. Dodaj još redova po potrebi.
export const COUNTRIES = [
  { code: "RS", dial: "+381", name: "Srbija" },
  { code: "ME", dial: "+382", name: "Crna Gora" },
  { code: "BA", dial: "+387", name: "Bosna i Hercegovina" },
  { code: "HR", dial: "+385", name: "Hrvatska" },
  { code: "MK", dial: "+389", name: "Severna Makedonija" },
  { code: "SI", dial: "+386", name: "Slovenija" },
  { code: "DE", dial: "+49", name: "Nemačka" },
  { code: "AT", dial: "+43", name: "Austrija" },
  { code: "CH", dial: "+41", name: "Švajcarska" },
  { code: "IT", dial: "+39", name: "Italija" },
  { code: "FR", dial: "+33", name: "Francuska" },
  { code: "GB", dial: "+44", name: "Velika Britanija" },
  { code: "US", dial: "+1", name: "SAD" },
  { code: "RU", dial: "+7", name: "Rusija" },
  { code: "CN", dial: "+86", name: "Kina" },
  { code: "HU", dial: "+36", name: "Mađarska" },
  { code: "RO", dial: "+40", name: "Rumunija" },
  { code: "BG", dial: "+359", name: "Bugarska" },
  { code: "GR", dial: "+30", name: "Grčka" },
  { code: "SE", dial: "+46", name: "Švedska" },
];
